//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Client.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Point.
        /// </summary>
        public static string AddNewPoint {
            get {
                return ResourceManager.GetString("AddNewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the operation in the background service..
        /// </summary>
        public static string BackgroundServiceError {
            get {
                return ResourceManager.GetString("BackgroundServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Background Service, Please Wait....
        /// </summary>
        public static string ConnectingToBackgroundService {
            get {
                return ResourceManager.GetString("ConnectingToBackgroundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the background service lost. Please ensure the service is running..
        /// </summary>
        public static string ConnectionLostError {
            get {
                return ResourceManager.GetString("ConnectionLostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU FAN.
        /// </summary>
        public static string CpuFan {
            get {
                return ResourceManager.GetString("CpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 60.
        /// </summary>
        public static string ExampleTemp {
            get {
                return ResourceManager.GetString("ExampleTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch fan settings!.
        /// </summary>
        public static string FailedToFetchFanSettings {
            get {
                return ResourceManager.GetString("FailedToFetchFanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Control.
        /// </summary>
        public static string FanControl {
            get {
                return ResourceManager.GetString("FanControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Curves.
        /// </summary>
        public static string FanCurves {
            get {
                return ResourceManager.GetString("FanCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU FAN.
        /// </summary>
        public static string GpuFan {
            get {
                return ResourceManager.GetString("GpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while communicating with the service..
        /// </summary>
        public static string IoError {
            get {
                return ResourceManager.GetString("IoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode is disabled because the temperature sensor could not be detected..
        /// </summary>
        public static string ManualModeDisabledTooltip {
            get {
                return ResourceManager.GetString("ManualModeDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode change request was rejected by the service or your hardware cannot apply this mode right now..
        /// </summary>
        public static string MuxChangeRejected {
            get {
                return ResourceManager.GetString("MuxChangeRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated graphics is completely disabled. Minimizes frame latency for maximum gaming performance, but increases battery consumption..
        /// </summary>
        public static string MuxDescDiscrete {
            get {
                return ResourceManager.GetString("MuxDescDiscrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated (iGPU) and discrete (dGPU) graphics dynamically switch based on load. Provides power saving for daily use and performance under load..
        /// </summary>
        public static string MuxDescHybrid {
            get {
                return ResourceManager.GetString("MuxDescHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA&apos;s dynamic graphics switching technology. Can put the discrete card to sleep or wake it up based on system load..
        /// </summary>
        public static string MuxDescOptimus {
            get {
                return ResourceManager.GetString("MuxDescOptimus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete graphics card is completely disabled. Ideal for maximum battery life and minimum heating..
        /// </summary>
        public static string MuxDescUMA {
            get {
                return ResourceManager.GetString("MuxDescUMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined graphics mode..
        /// </summary>
        public static string MuxDescUndefined {
            get {
                return ResourceManager.GetString("MuxDescUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mode successfully queued. You may need to restart your system for changes to take effect..
        /// </summary>
        public static string MuxModeQueued {
            get {
                return ResourceManager.GetString("MuxModeQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete.
        /// </summary>
        public static string MuxNameDiscrete {
            get {
                return ResourceManager.GetString("MuxNameDiscrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string MuxNameHybrid {
            get {
                return ResourceManager.GetString("MuxNameHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimus.
        /// </summary>
        public static string MuxNameOptimus {
            get {
                return ResourceManager.GetString("MuxNameOptimus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMA.
        /// </summary>
        public static string MuxNameUMA {
            get {
                return ResourceManager.GetString("MuxNameUMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mux Switch.
        /// </summary>
        public static string MuxSwitch {
            get {
                return ResourceManager.GetString("MuxSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing MUX Switch settings modifies hardware levels and may require a system reboot or sign out..
        /// </summary>
        public static string MuxWarningMessage {
            get {
                return ResourceManager.GetString("MuxWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add or remove temperature points. Fan speeds can be adjusted by dragging the points on the main graph..
        /// </summary>
        public static string PointEditorDescription {
            get {
                return ResourceManager.GetString("PointEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A point at {0}°C already exists..
        /// </summary>
        public static string PointExistsWarning {
            get {
                return ResourceManager.GetString("PointExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Point Settings.
        /// </summary>
        public static string PointSettingsTitleFormat {
            get {
                return ResourceManager.GetString("PointSettingsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Apply.
        /// </summary>
        public static string SaveAndApply {
            get {
                return ResourceManager.GetString("SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found! Please ensure the Nexus Hardware Service is running in the background..
        /// </summary>
        public static string ServiceNotFoundWarning {
            get {
                return ResourceManager.GetString("ServiceNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Statistics.
        /// </summary>
        public static string SystemStats {
            get {
                return ResourceManager.GetString("SystemStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between 1 and 99 °C..
        /// </summary>
        public static string TempBoundsWarning {
            get {
                return ResourceManager.GetString("TempBoundsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (°C).
        /// </summary>
        public static string TemperatureCelsius {
            get {
                return ResourceManager.GetString("TemperatureCelsius", resourceCulture);
            }
        }
    }
}
