<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<NeutralLanguage>en-US</NeutralLanguage>
		<ImplicitUsings>enable</ImplicitUsings>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishReadyToRun>true</PublishReadyToRun>
		<SelfContained>true</SelfContained>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<DebugType>embedded</DebugType>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<ApplicationIcon>wwwroot/icons/favicon.ico</ApplicationIcon>
		<AssemblyName>Nexus App</AssemblyName>
		<Version>0.0.0-dev</Version>
	</PropertyGroup>

	<PropertyGroup>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-All</AnalysisLevel>
		<NoWarn>$(NoWarn);CA1716</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="InfiniLore.InfiniFrame.BlazorWebView" Version="0.13.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.9" />
		<PackageReference Include="MudBlazor" Version="9.6.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nexus.Shared\Nexus.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Lang.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Lang.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Lang.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Lang.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
